  version: '3'
  services:
    nginx:
      container_name: webapp
      restart: unless-stopped
      image: nginx:latest
      ports:
        - "4443:443"
      volumes:
        - ./conf.d:/etc/nginx/conf.d/
        - ./certs:/etc/certs/
        - ./www:/var/www/