services:
    nginx:
        dns:
            - 8.8.8.8
            - 8.8.4.4
        container_name: ado
        restart: unless-stopped
        image: nginx:latest
        ports:
            - 8003:80
        depends_on:
            - ado
        volumes:
            - ./conf.d:/etc/nginx/conf.d/
            - ./certs:/etc/certs/
            - ./www:/var/www/
            - __WWW_ROOT__:/var/www/
    ado:
        build:
            context: ./ado
        restart: unless-stopped
        expose:
            - "7681"
